# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Create Labels'
description: '🤔 Auto create labels according to the repository path.'
author: 'xrkffgg'

branding:
  # https://feathericons.com/
  # e.g. https://haya14busa.github.io/github-action-brandings/
  icon: 'command'
  color: 'yellow'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true

#outputs:
#  result:
#    description: action result

runs:
  using: 'node12'
  main: 'dist/index.js'
